# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pGp9FGztKoP7GOZNavxd40u4e_7-S_L
"""

community_labels = ["A", "A", "B", "A", "A", "C", "A", "B", "A", "A"]

print("User Community Labels:", community_labels)

def boyer_moore_majority(arr):
    candidate = None
    count = 0

    # Phase 1: Find candidate
    for item in arr:
        if count == 0:
            candidate = item
        count += 1 if item == candidate else -1

    # Phase 2: Verify (optional)
    if arr.count(candidate) > len(arr) // 2:
        return candidate
    else:
        return None

majority = boyer_moore_majority(community_labels)
print("Majority Community in Network:", majority)

import pandas as pd
import random

# How many fake users you want
num_users = 1000   # You can increase to 2000 or 5000 if you want

# Community distribution (majority: A)
community_distribution = {
    "A": 0.55,  # 55%
    "B": 0.25,  # 25%
    "C": 0.15,  # 15%
    "D": 0.05   # 5%
}

communities = []
for _ in range(num_users):
    r = random.random()
    if r < community_distribution["A"]:
        communities.append("A")
    elif r < community_distribution["A"] + community_distribution["B"]:
        communities.append("B")
    elif r < community_distribution["A"] + community_distribution["B"] + community_distribution["C"]:
        communities.append("C")
    else:
        communities.append("D")

# Create DataFrame
df = pd.DataFrame({
    "user_id": range(1, num_users + 1),
    "community": communities
})

# Save CSV
df.to_csv("my_social_network.csv", index=False)

df.head()

from google.colab import files
files.download("my_social_network.csv")

import pandas as pd

df = pd.read_csv("my_social_network.csv")
labels = df["community"].tolist()

def boyer_moore_majority(arr):
    candidate = None
    count = 0

    for x in arr:
        if count == 0:
            candidate = x
        count += 1 if x == candidate else -1

    if arr.count(candidate) > len(arr) // 2:
        return candidate
    return None

majority = boyer_moore_majority(labels)
print("Majority Community:", majority)